files:
  - name: package.json
    strategy: chunks
    patterns:
      - pattern: |
          \s+"name": ".*?",
          \s+"version": ".*?",
        strategy: ours
  - name: VERSION
    strategy: ours
  - name: README.md
    strategy: ours
  - name: CHANGELOG.md
    strategy: changelog
  - name: esm/*
    strategy: ours
  - name: cjs/*
    strategy: ours
  - name: src/stripe.core.ts
    strategy: chunks
    patterns:
      - pattern: "\\s+Stripe.PACKAGE_VERSION = '.*?';"
        strategy: ours
