name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - v[0-9]+

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract tag message
      run: |
        git fetch --tags --force
        echo "$(git tag -l --format='%(contents:body)' ${{ github.ref_name }})" > "${{ runner.temp }}/release_notes.md"

    - name: Fetch app installation token
      uses: tibdex/github-app-token@v1.5.2
      id: gh-api-token
      with:
        app_id: ${{ secrets.GH_APP_STRIPE_OPENAPI_APP_ID }}
        private_key: ${{ secrets.GH_APP_STRIPE_OPENAPI_PRIVATE_KEY }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ runner.temp }}/release_notes.md
        token: ${{ steps.gh-api-token.outputs.token }}
